variable "ENVIRONMENT" {}
variable "LOCATION" {}
variable "LOCATION_CODE" {}
variable "PROJECT" {}
variable "PROJECT_CODE" {}
variable "PROJ_VNET_ADDRESS_SPACE_1" {}
variable "PROJ_VNET_ADDRESS_SPACE_2" {}
variable "AKS_SUBNET_IP_PREFIX" {}
variable "SVC_SUBNET_IP_PREFIX" {}
variable "AKS_DEFAULT_NODEPOOL" {}
variable "AKS_SERVICE_CIDR" {}
variable "TENANT_ID" {}
variable "SUBSCRIPTION_ID" {}
variable "AKS_VERSION" {}
variable "AKS_DOCKER_BRIDGE_ADDRESS" {}
variable "AKS_DNS_SERVICE_IP" {}
variable "CLIENT_ID" {}
variable "CLIENT_SECRET" {}
